# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(290, 200)
        MainWindow.setMinimumSize(QtCore.QSize(290, 200))
        MainWindow.setMaximumSize(QtCore.QSize(290, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/favicon/images/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gb_Settings = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_Settings.setGeometry(QtCore.QRect(10, 10, 270, 120))
        self.gb_Settings.setObjectName("gb_Settings")
        self.formLayoutWidget = QtWidgets.QWidget(self.gb_Settings)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lbl_URL = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_URL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_URL.setObjectName("lbl_URL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_URL)
        self.le_URL = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_URL.setMinimumSize(QtCore.QSize(0, 25))
        self.le_URL.setMaximumSize(QtCore.QSize(16777215, 25))
        self.le_URL.setObjectName("le_URL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.le_URL)
        self.le_Username = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_Username.setMinimumSize(QtCore.QSize(0, 25))
        self.le_Username.setMaximumSize(QtCore.QSize(16777215, 25))
        self.le_Username.setObjectName("le_Username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_Username)
        self.le_Password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_Password.setMinimumSize(QtCore.QSize(0, 25))
        self.le_Password.setMaximumSize(QtCore.QSize(16777215, 25))
        self.le_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_Password.setObjectName("le_Password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_Password)
        self.lbl_Username = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Username.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Username.setObjectName("lbl_Username")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_Username)
        self.lbl_Password = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_Password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Password.setObjectName("lbl_Password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_Password)
        self.lbl_com = QtWidgets.QLabel(self.gb_Settings)
        self.lbl_com.setGeometry(QtCore.QRect(240, 20, 31, 25))
        self.lbl_com.setObjectName("lbl_com")
        self.pb_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pb_Start.setGeometry(QtCore.QRect(10, 140, 270, 25))
        self.pb_Start.setObjectName("pb_Start")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionKullan_c_lar = QtWidgets.QAction(MainWindow)
        self.actionKullan_c_lar.setObjectName("actionKullan_c_lar")
        self.actionHakk_mda = QtWidgets.QAction(MainWindow)
        self.actionHakk_mda.setObjectName("actionHakk_mda")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Virtual Football"))
        self.gb_Settings.setTitle(_translate("MainWindow", "Settings"))
        self.lbl_URL.setText(_translate("MainWindow", "URL :           https://"))
        self.le_URL.setPlaceholderText(_translate("MainWindow", "superbet666"))
        self.lbl_Username.setText(_translate("MainWindow", "Username :"))
        self.lbl_Password.setText(_translate("MainWindow", "Password :"))
        self.lbl_com.setText(_translate("MainWindow", ".com"))
        self.pb_Start.setText(_translate("MainWindow", "Start"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionKullan_c_lar.setText(_translate("MainWindow", "Kullanıcılar"))
        self.actionHakk_mda.setText(_translate("MainWindow", "Hakkımda"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
